Add build stop on done and refresh SCM repo on pipeline save
screwdriver-cd/models pull request #106
Opened 2016-09-21 21:41 UTC by stjohnjohnson

2016-09-21 23:50 UTC, d2lam commented on lib/build.js
> +        return prom
You need `prom` so that it only returns after the above promises resolve?

2016-09-21 23:50 UTC, d2lam commented on lib/build.js
> +     * Stop a build
What is the reason for not updating github status anymore?

2016-09-21 23:50 UTC, d2lam commented on lib/build.js
> +     * Check if a build is doesntMatter
doesntMatter?

2016-09-21 23:58 UTC, d2lam requested changes

2016-09-22 00:02 UTC, stjohnjohnson commented on lib/build.js
> +     * Stop a build
So that stop just stops the build, update is the funnel for updating github status.

2016-09-22 00:03 UTC, stjohnjohnson commented on lib/build.js
> +        return prom
I need it so I can conditionally chain events.

2016-09-22 00:15 UTC, d2lam commented on lib/pipeline.js
> +        if (!this.isDirty('scmUrl')) {
Wouldn't this skip the very first time?

2016-09-22 00:16 UTC, d2lam requested changes

2016-09-22 00:24 UTC, d2lam approved these changes
👍  LGTM

2016-09-22 03:04 UTC, merged