[WIP] Add scmRepo to pipeline
screwdriver-cd/models pull request #110
Opened 2016-09-24 01:21 UTC by catto

I added a `scmRepo` to a modelConfig for a pipeline. screwdriver-cd/screwdriver#160
I'm not sure this is correct but I think I shouldn't call getRepoId at [here](https://github.com/screwdriver-cd/screwdriver/pull/204/files#diff-1eb6375f360812e82460d42f926123b1L77).

2016-09-24 05:24 UTC, stjohnjohnson commented
Why not use the new function added here: https://github.com/screwdriver-cd/models/pull/106/files

2016-09-24 05:37 UTC, catto commented
Ahh.. I completely misunderstood.
I'll change these to use `refreshScmRepo` and add duplicate checking instead of it.

2016-09-24 06:07 UTC, catto commented
Hmm.. we can call `refreshScmRepo` if a pipeline already exists. But `id` for new pipeline will be generated using `scmRepo.id` before a creation of new pipeline. So can't call `refreshScmRepo` and need to get scmRepo and call `baseFactory.create` with scmRepo, don't we?

2016-09-26 06:51 UTC, stjohnjohnson commented
@catto where can we move that function then?  Maybe make it static somehow?

2016-09-26 12:29 UTC, catto commented
@stjohnjohnson 🙆 I'll fix them.
I was just wondering if you had design discussions and how much I can change the code.

2016-09-26 15:51 UTC, catto commented
I made it static and added duplication checks. If they are okay, I will change pipeline plugin to catch the error and return a conflict error.

2016-09-28 18:42 UTC, petey requested changes

2016-09-28 18:42 UTC, petey commented on lib/pipeline.js
> +    getFirstAdminName() {
`getFirstAdminName`, and `getAdmin` should appear in source order before they are used (in `get admin`)

2016-09-28 18:42 UTC, petey commented on lib/pipeline.js
> +    static getScmRepo(username, scm, scmUrl) {
`getScmRepo` should appear in source order before it is used

2016-09-28 18:42 UTC, petey commented on lib/pipelineFactory.js
> +        return Pipeline.getScmRepo(admin, this.scmPlugin, config.scmUrl)
I don't really understand why this is something the pipeline model has to be a part of, other than it is a convenient place to have static methods to get a user model. 

On the other hand, the pipelineFactory could have a method that fetches a user model, and scmPlugin could have a method `getRepoData(userModel, scmUrl)` or whatever that does the lookup.

2016-10-01 19:16 UTC, catto commented on lib/pipelineFactory.js
> +        return Pipeline.getScmRepo(admin, this.scmPlugin, config.scmUrl)
That's reasonable. I have moved `getScmRepo` to the pipelineFactory. I think `getRepoData` in the scmPlugin is not necessary in this case.

2016-10-13 01:28 UTC, petey commented
Closing in favor of work in #120

2016-10-13 01:28 UTC, closed without merging