Remove hoek.applyToDefaults on complex objects
screwdriver-cd/models pull request #119
Opened 2016-10-10 22:28 UTC by petey

`hoek.applyToDefaults` does numerous clones of input objects over the course of merging into a single output. This has negative effects when dealing with the sequalize module as an SCM ORM. This PR removes the use of that method for all complex objects.

2016-10-10 22:31 UTC, stjohnjohnson approved these changes
LGTM.  I hope we don't run into more issues. 

![](http://media1.giphy.com/media/BFs38lXZQSRVK/200w.gif)

2016-10-10 23:20 UTC, d2lam requested changes

2016-10-10 23:20 UTC, d2lam commented on lib/baseFactory.js
> +                c.datastore = this.datastore;
For this to do the exact same thing as before, shouldn't this block be:
```
c.datastore = this.datastore || config.datastore;
c.scm = this.scm || config.scm;
c.id = modelData.id || config.id;
```

2016-10-11 01:02 UTC, petey commented on lib/baseFactory.js
> +                c.datastore = this.datastore;
Since `this.datastore`, `this.scm`, and `modelData.id` are always defined, I don't really see the difference.

2016-10-11 01:19 UTC, d2lam approved these changes

2016-10-11 01:19 UTC, d2lam commented on lib/baseFactory.js
> +                c.datastore = this.datastore;
True. I'm fine with it.

2016-10-11 01:19 UTC, merged