Refactor models to use new scm-base functions
screwdriver-cd/models pull request #120
Opened 2016-10-12 22:10 UTC by tkyi

- Use `scmUri` over `scmUrl`
- Call `parseUrl` to get `scmUri`
- Call `decorateCommit`
- Make changes to conform to new eslint rules
- Bump data-schema version to 14.0.0
- Bump models version to 16.0.0

2016-10-12 22:13 UTC, FenrirUnbound commented
Thing to note is that `scm-github` hasn't adopted the new `scm-base@2.x` interface

2016-10-12 22:17 UTC, tkyi commented
@FenrirUnbound Should be okay if I bumped major versions for `models`, right?

2016-10-12 23:29 UTC, petey requested changes

2016-10-12 23:29 UTC, petey commented on lib/buildFactory.js
> +                        console.log('commit info: ', modelConfig.commit);
console.log

2016-10-13 03:17 UTC, d2lam requested changes

2016-10-13 03:17 UTC, d2lam commented on lib/buildFactory.js
> +                config.modelConfig.sha = sha;
What is this for? It's not being used.

2016-10-13 03:17 UTC, d2lam commented on lib/pipeline.js
> +            this.checkoutUrl = null; // TODO: delete checkoutUrl?
Why?

2016-10-13 05:18 UTC, tkyi commented on lib/buildFactory.js
> +                config.modelConfig.sha = sha;
Do we not want to return the `sha` in the `build` blob?

2016-10-13 05:19 UTC, tkyi commented on lib/pipeline.js
> +            this.checkoutUrl = null; // TODO: delete checkoutUrl?
I don't think we want to save `checkoutUrl` permanently in the `pipeline` blob

2016-10-13 06:34 UTC, d2lam commented on lib/buildFactory.js
> +                config.modelConfig.sha = sha;
What do you mean? You're just setting the config.modelConfig.sha here. You're not returning or doing anything with it in this function.

2016-10-13 18:18 UTC, FenrirUnbound commented on lib/buildFactory.js
> +                config.modelConfig.sha = sha;
It looks like we're modifying a parameter, which is a code smell. The function already passes back the SHA, as well as additional data regarding the SHA. 

Why do we want the function to also mutate a given parameter?

2016-10-13 18:27 UTC, tkyi commented on lib/buildFactory.js
> +                config.modelConfig.sha = sha;
Changed the function to return an object with the decorated commit and the SHA.

The decorated commit does not include a SHA.

2016-10-13 18:42 UTC, d2lam approved these changes
LGTM 👍

2016-10-13 19:31 UTC, petey approved these changes

2016-10-13 19:32 UTC, merged