Add event model
screwdriver-cd/models pull request #126
Opened 2016-10-27 18:12 UTC by d2lam

- Create an event would need `pipelineId, sha, workflow, username, [causeMessage]`
- It would create: 
```json
{
    "pipelineId": "12345f642bbfd1886623964b4cff12db59869e5d",
    "sha": "ccc49349d3cffbd12ea9e3d41521480b4aa5de5f",
    "createTime": "2038-01-19T03:14:08.131Z",
    "commit": {
        "url": "https://link.to/commitDiff",
        "message": "some commit message that is here",
        "author": {
            "avatar": "https://avatars.githubusercontent.com/u/1234567?v=3",
            "name": "Batman",
            "url": "https://internal-ghe.mycompany.com/imbatman",
            "username": "imbatman"
        }
    },
    "workflow": ["main", "publish"],
    "causeMessage": "Merge pull request #26 from screwdriver-cd/models",
    "creator": {
        "avatar": "https://avatars.githubusercontent.com/u/2042?v=3",
        "name": "St John",
        "url": "https://github.com/stjohn",
        "username": "stjohn"
    }
}
```
- Add getBuilds for event
- Add getEvents for pipeline

2016-10-27 19:41 UTC, petey approved these changes
I think this is ok for now. We can revisit later if there are any necessary updates.

2016-10-27 23:08 UTC, minzcmu requested changes

2016-10-27 23:08 UTC, minzcmu commented on README.md
> +    "causeMessage": "Merge pull request #26 from screwdriver-cd/models",
type?

2016-10-27 23:08 UTC, minzcmu commented on lib/eventFactory.js
> +     * @param  {Object}    config.datastore     Object that will perform operations on the datastore
config.scm?

2016-10-27 23:08 UTC, minzcmu commented on lib/eventFactory.js
> +            if (!pipeline) {
API should take care of these checks. If throws errors here, when api catches it, it will be 500, probably not we want

2016-10-27 23:08 UTC, minz1027 commented on lib/pipeline.js
> +    getEvents(config) {
Update README.md for pipeline?

2016-10-27 23:08 UTC, minz1027 commented on package.json
> +    "screwdriver-data-schema": "^14.2.0",
should be 15.0.0
https://github.com/screwdriver-cd/data-schema/pull/84/files

2016-10-27 23:19 UTC, d2lam commented on README.md
> +    "causeMessage": "Merge pull request #26 from screwdriver-cd/models",
It's thereeeee

2016-10-28 17:32 UTC, d2lam commented on lib/pipeline.js
> +    getEvents(config) {
Updated - for other ones too

2016-10-28 18:07 UTC, minzcmu approved these changes

2016-10-28 18:12 UTC, petey requested changes

2016-10-28 18:12 UTC, petey commented on README.md
> +Abort running steps. If no steps ever ran, abort the first step
`abortSteps` is used internally to the model. There's no use case to expose it.

2016-10-28 18:28 UTC, d2lam commented on README.md
> +Abort running steps. If no steps ever ran, abort the first step
@petey  Then we should make it private. Right now it is exposed.

2016-10-28 22:00 UTC, d2lam commented on README.md
> +Abort running steps. If no steps ever ran, abort the first step
@petey  I moved it

2016-10-31 18:13 UTC, petey approved these changes

2016-10-31 21:34 UTC, merged