feat(379): move addWebhook out of sync
screwdriver-cd/models pull request #146
Opened 2016-12-21 01:28 UTC by d2lam

Move addWebhook outside of `sync()` to reduce overhead since this method is called many times at different places. We can call `pipeline.addWebhook()` once inside `create` right before `sync`: https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/create.js#L92

We can also add another endpoint inside `api` for correcting webhooks if needed.

2016-12-21 01:36 UTC, minzcmu requested changes

2016-12-21 01:36 UTC, minz1027 commented on README.md
>  #### Get Jobs
Add the reamde for addWebhook please :)

2016-12-21 01:40 UTC, tkyi approved these changes
![](http://media1.giphy.com/media/rhkf8WWay7VZK/200w.gif)

2016-12-21 06:56 UTC, stjohnjohnson requested changes

2016-12-21 06:56 UTC, stjohnjohnson commented on lib/pipeline.js
> +                webhookUrl: 'https://api.screwdriver.cd/v4/webhooks'
Please don't hardcode the API endpoint.

2016-12-21 07:10 UTC, d2lam commented on README.md
>  #### Get Jobs
Added

2016-12-21 07:23 UTC, d2lam commented on lib/pipeline.js
> +                webhookUrl: 'https://api.screwdriver.cd/v4/webhooks'
Do you suggest take in a parameter in this function and from the API pass in `request.server.info.uri`?

2016-12-22 04:10 UTC, minzcmu approved these changes

2016-12-22 06:40 UTC, stjohnjohnson approved these changes

2016-12-22 19:12 UTC, merged