[WIP] feat: Add syncPRs() for pipeline
screwdriver-cd/models pull request #148
Opened 2017-01-07 01:16 UTC by d2lam

There are 3 cases:
- `PR-1` is closed, but it's still in the current list of jobs, so archive it. Related: https://github.com/screwdriver-cd/screwdriver/issues/389
- `PR-1` is opened, but it's not in the current list of jobs, so create it. 
- `PR-1` is opened, it's in the current list of jobs, but it was archived, so update it. 

Mocking `this.scm.getOpenedPRs`. This should return the list of opened PR jobs, for example: `['PR-12', PR-20']`
Need some feedback on how to simplify the logic or if this is fine.

2017-01-09 22:49 UTC, FenrirUnbound commented
Looking over the logic, it seems like the flow goes something like:

1. Sort the PRs
2. Do stuff with the PR
  2.a. Archive
  2.b Create
  2.c Update

One approach you could take is to map-reduce. Have a function that accomplishes *Task 1* and splits the PRs into 3 lists. Each of the operations in *Task 2* could be a separate function that, given a set of jobs, performs that operation.

2017-01-09 23:13 UTC, d2lam commented
@FenrirUnbound  I'm not sure what you meant.
It's currently 2 parts:
- Get a list of actual opened PRs (by contacting SCM). For example: ['PR-2'] --- list A
- Get a list of PRs that Screwdriver thinks are opened. For example: ['PR-1', 'PR-3'] --- list B

Then there are 3 scenarios like I mentioned:
- `PR-2` is already closed. If it's in list B, then archive it. If not, then it's fine. 
- `PR-2` is opened. If it's not in list B, then create it. If it's in list B and archived, then unarchive it. If it's in list B and not archived, then it's fine.

2017-01-10 00:23 UTC, FenrirUnbound commented
Right. The initial promise chain starts by fetching all of the PRs: which PRs are actually open and which PRs we previously thought were open. That's a prerequisite to the remaining scenarios.

My suggested Task 1 would -- given a PR's state -- determine if it needs to be archived, created, or updated. It wouldn't actually do those actions; it would just sort the PRs into different lists.

Task 2 would be where all those PRs would be processed. This would be the area where the archiving happens, or creations occurs, or when the information is updated.

2017-01-10 00:27 UTC, FenrirUnbound commented
Pseudo-code:

```
Promise.all([
  this.jobs,
  this.scm.getOpenedPRs({
    scmUri: this.scmUri,
    token
  }),
  this.getConfiguration()
]).then(([existingJobs, openPrs, config]) => {
  const [toArchive, toCreate, toUpdate] = checkPrState(existingJobs, openPrs, config)

  return Promise.all([
    archivePr(toArchive),
    createPr(toCreate),
    updatePr(toUpdate)
  ]);
});

```

2017-01-10 00:51 UTC, d2lam commented
@FenrirUnbound  Got it! 👍

2017-01-10 01:48 UTC, d2lam commented
@FenrirUnbound  I refactored the code in a separate commit. Will squash later. Please help re-review! :)

2017-01-11 00:05 UTC, FenrirUnbound requested changes

2017-01-11 00:05 UTC, FenrirUnbound commented on lib/pipeline.js
> +                const jobList = checkPrState(existingJobs, openedPRs, config);
You're not using `config` in the `checkPrState` function

2017-01-11 00:10 UTC, FenrirUnbound commented on lib/pipeline.js
> +function updateJob(jobList, archived) {
Minor: `updateJob` doesn't update the whole job. Maybe "updateJobArchive"?

2017-01-11 00:22 UTC, d2lam commented on lib/pipeline.js
> +                const jobList = checkPrState(existingJobs, openedPRs, config);
Good catch! 👍

2017-01-11 22:15 UTC, d2lam commented
@FenrirUnbound  Thanks for your suggestions! :) Please re-review! :D

2017-01-12 21:35 UTC, FenrirUnbound approved these changes
👍 

Looks good!

![giphy 39](https://cloud.githubusercontent.com/assets/721148/21909253/f6a9e948-d8cb-11e6-897f-a05e0bafb9cd.gif)

2017-01-12 21:36 UTC, FenrirUnbound commented
Are you planning on waiting for the SCM modules to catch up and implement the extra endpoint?

2017-01-12 23:05 UTC, d2lam commented
@FenrirUnbound  Just rewrote some parts due to the extra requirements from scm-base. Please help re-review :) 

And yeah want to merge in this order: scm-base -> scm-github/scm-bitbucket -> models -> API

2017-01-13 00:46 UTC, FenrirUnbound approved these changes
👍 

Still looks good to me! 😸

2017-01-13 02:04 UTC, minzcmu approved these changes
👍 LGTM

2017-01-13 02:05 UTC, merged