[DNM][WIP] feat: add template model
screwdriver-cd/models pull request #149
Opened 2017-03-01 01:50 UTC by minz1027

Blocked by changes to be done in data-schema

Related to https://github.com/screwdriver-cd/screwdriver/issues/470

2017-03-03 23:58 UTC, d2lam requested changes

2017-03-03 23:58 UTC, d2lam commented on README.md
> +    config: 'image: node:6',
object

2017-03-03 23:58 UTC, d2lam commented on README.md
> +| config.config | String | Yes | Config of the screwdriver-template.yaml |
object

2017-03-03 23:58 UTC, d2lam commented on lib/templateFactory.js
> +     * @param  {String}     config.config        Config of the screwdriver-template.yaml
object

2017-03-03 23:58 UTC, d2lam commented on lib/templateFactory.js
> +        const c = config;
remove this

2017-03-04 01:00 UTC, FenrirUnbound commented on README.md
> +    name: 'testTemplate',
Question: does this mean that we're not namespacing templates?

2017-03-04 01:00 UTC, FenrirUnbound commented on README.md
> +    name: 'testTemplate',
I would have expected a `namespace/template_name` format being enforced

2017-03-04 01:07 UTC, FenrirUnbound requested changes

2017-03-04 01:07 UTC, FenrirUnbound commented on lib/templateFactory.js
> +     * @param  {Array}      config.labels        Labels attached to the template
The `README` states that this is optional, but the JSDoc does not reflect that. Which one is it?/

2017-03-04 02:21 UTC, tkyi commented on README.md
> +    name: 'testTemplate',
I'm not sure if we ever figured out how to police/enforce naming conventions for templates

2017-03-04 02:21 UTC, tkyi commented on README.md
> +    name: 'testTemplate',
But yeah I think St. John was envisioning some sort of `platform/step` sort of format

2017-03-06 17:57 UTC, minz1027 commented on lib/templateFactory.js
> +     * @param  {Array}      config.labels        Labels attached to the template
fixed. Should be optional

2017-03-06 17:59 UTC, minz1027 commented on README.md
> +    name: 'testTemplate',
@tkyi @FenrirUnbound I am not sure if we should enforce platform/step or let the platform owner to decide what is the proper format. If `platform/step` then we need to change the `data-schema`

2017-03-06 18:30 UTC, minz1027 commented on README.md
> +    name: 'testTemplate',
The naming issue will be addressed in next pass.

2017-03-06 18:30 UTC, FenrirUnbound approved these changes
👍 

![giphy 51](https://cloud.githubusercontent.com/assets/721148/23623730/f5902bca-0257-11e7-9ea1-14fc7875f692.gif)

2017-03-06 18:32 UTC, d2lam approved these changes
LGTM 👍

2017-03-06 18:33 UTC, merged