feat(470): Add version bumping to template creation
screwdriver-cd/models pull request #152
Opened 2017-03-15 20:53 UTC by jerryzhang222

Move auto-bumping of template version from API to models.

Related: https://github.com/screwdriver-cd/screwdriver/pull/497

**Pasted from Above PR:**

Auto bump version:
For example, if latest version is 1.7.3

If template.yaml says 1, it will create 1.7.4
If template.yaml says 1.7, it will create 1.7.4
If template.yaml says 1.7.3, it will create 1.7.4 (does not matter what the patch is)
If template.yaml says 1.8, it will create 1.8.0
If template.yaml says 2, it will create 2.0.0

Related: https://github.com/screwdriver-cd/screwdriver/issues/470

2017-03-15 23:51 UTC, minzcmu requested changes

2017-03-15 23:51 UTC, minz1027 commented on lib/templateFactory.js
> +                    latestMatch[PATCH_MATCH].slice(1), 10) + 1;
Can u try put it in the same line?

2017-03-16 00:19 UTC, minzcmu approved these changes
👍 LGTM

2017-03-16 00:25 UTC, d2lam approved these changes

2017-03-16 00:25 UTC, merged

2017-03-16 00:27 UTC, FenrirUnbound commented on lib/templateFactory.js
> +        const match = VERSION_REGEX.exec(config.version);
We should be using the `semver` module for handling all the version magic