fix(tokens): Use URL-safe values, add toJson
screwdriver-cd/models pull request #171
Opened 2017-06-06 22:19 UTC by ian-fox

* add `toJson` to hide the hash value, since the only time the API ever even knows a hash value exists is to delete it before returning the token, and so that `value` doesn't have to be added manually by the API
* switch base64 encoding to be URL-safe. Could use a library like `base64url`, but the same thing can be accomplished by a small function in one file, which doesn't add a new dependency. If adding the dependency for increased code-cleanliness is preferred I can switch to that though.
* test still had `password` in it, we no longer use that in tokens

2017-06-06 22:56 UTC, minzcmu requested changes

2017-06-06 22:56 UTC, minz1027 commented on lib/generateToken.js
> + * @param  {String} token
should have `@method`

2017-06-06 23:08 UTC, ian-fox commented
Just now saw @FenrirUnbound's comment [here](https://github.com/screwdriver-cd/data-schema/pull/140#discussion_r120495728), switching to use the library.

2017-06-07 00:01 UTC, r3rastogi approved these changes
Looks good

2017-06-07 00:42 UTC, tkyi approved these changes
![](https://media2.giphy.com/media/6CCREJehKQ6ME/200w.gif)

2017-06-07 00:44 UTC, minzcmu approved these changes

2017-06-07 00:44 UTC, merged