[DNM] fix(616): Add template tag model
screwdriver-cd/models pull request #179
Opened 2017-07-12 01:35 UTC by tkyi

## Context

Users would like to tag their template versions with words such as "latest" or "stable" (much like Docker tags work).

## Objective

This PR adds a TemplateTag and TemplateTagFactory model.

## Related Links
Blocked by: https://github.com/screwdriver-cd/data-schema/pull/157
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/616

2017-07-14 00:02 UTC, minzcmu requested changes

2017-07-14 00:02 UTC, minz1027 commented on lib/templateTag.js
> +    constructor(config) {
Should have `name`, `tag`, `version` here in the param

2017-07-14 00:02 UTC, minz1027 commented on lib/templateTagFactory.js
> +     * @return {Job}
{TemplateTag}

2017-07-14 01:09 UTC, tkyi commented on lib/templateTagFactory.js
> +     * @return {Job}
oops

2017-07-14 18:00 UTC, FenrirUnbound commented on README.md
> +model.update()
Showing that you're changing a model's value then calling update would be more valuable

2017-07-14 18:02 UTC, FenrirUnbound commented
I guess I'm not understanding the implementation in full.

So there is a separate `TemplateTag` model. This sounds like we're making a new table between templates and tag names, but I'm not sure that's actually the intention. Why did we choose to make an independent model for template tags?

2017-07-14 18:04 UTC, FenrirUnbound commented
The other thing I've noticed is that your example says we should instantiate the Factory independently of a template. I cannot think of a situation where we would want the `TagTemplate` independent of the `Template` it's associated with. What scenarios do we expect where we would want just the `TagTemplate` and not also want the `Template` model?

2017-07-14 18:08 UTC, FenrirUnbound commented
Lastly, the label for this PR says "minor", but the PR header and the commit both use "fix".

2017-07-14 22:44 UTC, tkyi commented
@FenrirUnbound Yes the implementation details are mentioned in the issue: https://github.com/screwdriver-cd/screwdriver/issues/616#issuecomment-314568245
We are making another table that just maps between template names, versions, and tags.

We would use a `TagTemplate` without the `Template` model when deleting a tag.

I can change the commit message to `feat`.

2017-07-14 22:53 UTC, FenrirUnbound commented on lib/templateTagFactory.js
> +     * @param  {String}     config.name          The template name
Why does the factory need all of these variables?

2017-07-14 22:54 UTC, FenrirUnbound commented on lib/templateTagFactory.js
> +     * @param  {String}     config.name          The template name
I would expect these more in the `.create()`

2017-07-14 23:23 UTC, FenrirUnbound commented
> We would use a TagTemplate without the Template model when deleting a tag. I'd take a look at the PRs open for the API to better understand the implementation details. (also linked above)

The DELETE route also requires a lookup for the `Template` 🤔: https://github.com/screwdriver-cd/screwdriver/pull/647/files#diff-9b71f6afabf90daef582f5ba13502794R43.

The point I was getting to was to prefer composition. If you're always going to have a `TemplateTag` associated with a `Template`, why not have the `TemplateTag` do the lookup in the same operation? Doing the lookups separately means we're paying two roundtrips to the datastore.

2017-07-15 00:06 UTC, tkyi commented on lib/templateTagFactory.js
> +     * @param  {String}     config.name          The template name
Put it in the wrong place earlier when addressing Min's comment 😆

2017-07-17 16:57 UTC, FenrirUnbound approved these changes
👍 

![zxcv](https://user-images.githubusercontent.com/721148/28279746-56df3f60-6ad6-11e7-831a-28f92a468383.gif)

2017-07-17 20:50 UTC, minzcmu approved these changes

2017-07-17 21:01 UTC, merged