[DNM] feat(653): support Blockedby
screwdriver-cd/models pull request #244
Opened 2018-05-11 23:05 UTC by d2lam

2018-05-15 21:34 UTC, minzcmu approved these changes
small comments

2018-05-15 21:36 UTC, minzcmu requested changes

2018-05-15 21:36 UTC, minz1027 commented on lib/build.js
> +    if (!blockedByNames) {
This can be empty array, also need to check the length

2018-05-15 23:19 UTC, pranavrc approved these changes

2018-05-16 17:44 UTC, minzcmu approved these changes

2018-05-16 19:15 UTC, d2lam commented
To address Pranav's comment in the worker (https://github.com/screwdriver-cd/queue-worker/pull/60#pullrequestreview-120466218), this now also pass the `jobId`. Please re-review the last commit. :d2thanks

2018-05-16 22:31 UTC, tkyi commented on lib/build.js
> +function findIdsOfMatchedJobs(jobs, jobnames) {
`jobNames`

2018-05-16 23:49 UTC, pranavrc approved these changes
![image](https://media.giphy.com/media/XuBJvrKHutnkQ/giphy.gif)

2018-05-18 18:51 UTC, Filbird approved these changes

2018-05-21 18:53 UTC, merged