add pr to event
screwdriver-cd/models pull request #246
Opened 2018-05-15 18:16 UTC by lusol

add pr url to returned event object

related pr: https://github.com/screwdriver-cd/screwdriver/issues/822

2018-05-15 18:23 UTC, tkyi requested changes
Can you add/modify a test?

2018-05-15 21:17 UTC, minzcmu requested changes
Commit message should start with `fix` or `feat`. And tests?

2018-05-15 21:37 UTC, lusol commented
added a small test

2018-05-15 21:45 UTC, pranavrc commented on lib/eventFactory.js
> +                if (config.prInfo) {
`if (config.prInfo && config.prInfo.url)  {` perhaps?

2018-05-15 22:50 UTC, lusol commented on lib/eventFactory.js
> +                if (config.prInfo) {
ok

2018-05-16 00:41 UTC, tkyi approved these changes
LGTM 👍

2018-05-16 22:20 UTC, minzcmu approved these changes
👍

2018-05-16 22:20 UTC, merged