feat(1113): Parse meta from config on event creation
screwdriver-cd/models pull request #265
Opened 2018-06-18 23:17 UTC by Filbird

## Context
Events should be created with the meta specified in the config.

## Objective
Create an `event` with `meta` if the field is populated.

## Reference
https://github.com/screwdriver-cd/screwdriver/issues/1113

2018-06-18 23:31 UTC, minzcmu approved these changes
tests?

2018-06-19 00:20 UTC, Filbird commented
:^)

2018-06-19 18:43 UTC, d2lam approved these changes

2018-06-19 23:59 UTC, minz1027 commented
Can you also add meta as an optional field for the jsDoc for buildFactory.create function? https://github.com/screwdriver-cd/models/blob/master/lib/buildFactory.js#L155

2018-06-20 00:59 UTC, Filbird commented
Ooh. Yep! Good catch

2018-06-21 21:15 UTC, minzcmu approved these changes

2018-06-21 22:19 UTC, jithine requested changes

2018-06-21 22:19 UTC, jithin1987 commented on test/lib/buildFactory.test.js
> -    describe('create', () => {
remove `only`

2018-06-22 00:03 UTC, jithine approved these changes

2018-06-22 00:06 UTC, merged