feat(1204): Add pagination for getting pipeline events only [2]
screwdriver-cd/models pull request #282
Opened 2018-08-09 21:24 UTC by tkyi

## Context
The pipeline page is taking a long time to load since there are so many events per pipeline. Pagination is only actually done through the UI, not from the API side. It would be nice to do pagination from the API side to speed up UI loading for the pipeline page.

## Objective
This PR will:
- remove pagination for all function calls except `getEvents` (since most functions rely on everything being returned)
- remove default pagination from baseFactory except when `config.pagination` is passed in

2 questions:
1. Not sure if we should default to `sort: descending` (the API will force that default anyways using the data-schema (https://github.com/screwdriver-cd/data-schema/blob/master/api/pagination.js#L18))
2. Not sure if we should always paginate pipeline `getEvents` since *A. it's unlikely people will want more than 50 events* and *B. it'll make the page load a lot faster* or we should default to no pagination for backwards compatibility.

## Related links
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1204

2018-08-13 17:20 UTC, minzcmu approved these changes

2018-08-13 17:39 UTC, minzcmu requested changes

2018-08-13 17:39 UTC, minz1027 commented on lib/pipeline.js
> +            };
Don't think we need this default pagination option here. Base factory will handle the default values.

2018-08-13 18:27 UTC, minzcmu approved these changes

2018-08-13 19:03 UTC, minzcmu requested changes

2018-08-13 19:03 UTC, minz1027 commented on lib/baseFactory.js
> +                count: hoek.reach(config, 'paginate.count', { default: PAGINATE_COUNT }),
This hoek.reach behaves weird when paginate.count = undefined.
```
> var config = { paginate: { count: undefined } }
>  hoek.reach(config, 'paginate.count', { default: 5 })
undefined
```
See it's not using the default value when paginate.count's value is `undefined`. We need to take care of that case as well.  need to do `hoek.reach(config, 'paginate.count', { default: PAGINATE_COUNT }) || PAGINATE_COUNT`. Not sure if there is any other way to do it to make it cleaner

2018-08-14 20:28 UTC, minzcmu approved these changes

2018-08-14 21:45 UTC, Filbird approved these changes

2018-08-14 21:47 UTC, merged

2018-08-14 21:52 UTC, d2lam commented on lib/baseFactory.js
> +                count: hoek.reach(config, 'paginate.count', { default: PAGINATE_COUNT })
`hoek.reach` doesn't seem to be useful here. Can just do `paginate.count || PAGINATE_COUNT`