fix(1271): Add option to return raw data for datastore scan
screwdriver-cd/models pull request #293
Opened 2018-10-05 00:01 UTC by tkyi

## Context
When trying to get all distinct namespaces in templates, you should get an array of namespace strings, instead of an array of template objects.

## Objective
This PR changes the `list` function to take in a flag to return raw data.

## Related links
Related to https://github.com/screwdriver-cd/screwdriver/issues/1271, https://github.com/screwdriver-cd/datastore-sequelize/pull/35

2018-10-05 20:32 UTC, minzcmu requested changes

2018-10-05 20:32 UTC, minz1027 commented on lib/baseFactory.js
> +        if (config && config.raw) {
Let's document this behavior in the readme too

2018-10-08 16:45 UTC, DekusDenial approved these changes

2018-10-08 20:22 UTC, minzcmu approved these changes

2018-10-08 20:22 UTC, merged