feat(675): Pass freezeWindows in config to executor
screwdriver-cd/models pull request #322
Opened 2019-01-31 00:20 UTC by pranavrc

This PR adds support for passing on the `freezeWindows` job setting to the executor.

Data Schema PR: https://github.com/screwdriver-cd/data-schema/pull/312
Config parser PR: https://github.com/screwdriver-cd/config-parser/pull/82
Related issue: https://github.com/screwdriver-cd/screwdriver/issues/675

2019-02-05 17:47 UTC, jithine approved these changes

2019-02-06 21:07 UTC, d2lam approved these changes

2019-02-08 22:21 UTC, d2lam requested changes
Don't you also need to pass in eventId because of this PR: https://github.com/screwdriver-cd/executor-queue/pull/40/files

2019-02-08 22:52 UTC, minzcmu approved these changes

2019-02-11 22:22 UTC, d2lam approved these changes

2019-02-11 22:59 UTC, merged