fix: pass jobId and pipelineId
screwdriver-cd/models pull request #444
Opened 2020-04-03 20:26 UTC by pritamstyz4ever

## Context

JobId and PipelineId were undefined in case of periodic builds in log message

## Objective

This PR passes jobId and pipelineId in function to log correctly

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-04-03 20:38 UTC, klu909 approved these changes

2020-04-03 21:09 UTC, tkyi requested changes
Shouldn't the job id and the pipeline id already be determined from the `pipeline` and `job` objects?
calling `postBuildEvent` in `startPeriodic`: https://github.com/screwdriver-cd/queue-service/blob/master/plugins/queue/put.js#L156
pipelineId: https://github.com/screwdriver-cd/queue-service/blob/master/plugins/queue/put.js#L25
jobId: https://github.com/screwdriver-cd/queue-service/blob/master/plugins/queue/put.js#L30

2020-04-03 21:24 UTC, jithine commented
I think this change is to satisfy the logger arguments, which is no not ideal https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L193, we could change the logger arguments instead.

2020-04-03 23:53 UTC, tkyi commented
Could the logger extrapolate the data from the config? Like 
`..${config.pipeline.id}:${config.job.id}`

2020-04-08 20:38 UTC, pritamstyz4ever commented
Fixed in executor-queue.  https://github.com/screwdriver-cd/executor-queue/pull/86
Closing PR

2020-04-08 20:39 UTC, closed without merging