Get active jobs for a pipeline
screwdriver-cd/models pull request #99
Opened 2016-09-16 23:29 UTC by d2lam

- Only lists active jobs (archived = false)
- Lists jobs in the order they appear in workflow, then open PRs.

Solves https://github.com/screwdriver-cd/screwdriver/issues/188

2016-09-18 16:49 UTC, stjohnjohnson commented on lib/pipeline.js
> +                parseInt(job1.name.slice(START_INDEX), 10) -
Why not make a method `job.PRnum` or something.

2016-09-18 16:49 UTC, stjohnjohnson commented on lib/pipeline.js
> +                count: PAGINATE_COUNT, // This limit is set by the matrix restriction
This is not correct, there is no 25 limit when you are asking for jobs + PRs.  You need to either ask for 100+ or iterate on this.

2016-09-18 16:50 UTC, stjohnjohnson commented on lib/pipeline.js
> +     * @return {[type]} [description]
Please fill in

2016-09-18 16:50 UTC, stjohnjohnson commented on lib/pipeline.js
> +    getActiveJobs() {
Why method vs. getter?  Are you passing info into this?

2016-09-18 16:50 UTC, stjohnjohnson requested changes

2016-09-18 16:52 UTC, stjohnjohnson commented
You should also update line 62 to archive jobs.  And what about where PRs get archived?

2016-09-18 17:08 UTC, d2lam commented on lib/pipeline.js
> +    getActiveJobs() {
Nothing get passed in so yes I can make it a getter.
Or we can make this take in archived = true or false and pagination. 

What would you prefer?

2016-09-18 17:08 UTC, d2lam commented on lib/pipeline.js
> +                count: PAGINATE_COUNT, // This limit is set by the matrix restriction
Sorry this is another copy pasta.

2016-09-18 17:08 UTC, d2lam commented on lib/pipeline.js
> +                parseInt(job1.name.slice(START_INDEX), 10) -
Good idea. I can do that.

2016-09-18 17:10 UTC, d2lam commented
@stjohnjohnson  This PR is just for getting active jobs. I was going to have the actual archiving in a separate PR.

2016-09-18 20:05 UTC, stjohnjohnson commented on lib/pipeline.js
> +    getActiveJobs() {
i like option 2, combine that with what we did for `jobs.getBuilds` maybe

2016-09-19 18:13 UTC, d2lam commented on lib/pipeline.js
> +    getActiveJobs() {
What do you mean combine with `jobs.getBuilds`?

2016-09-19 19:47 UTC, d2lam commented
@stjohnjohnson  Addressed your comments:
- Added a function `job.prNum()`
- Allow `getJobs` to take in a `config` param. It get jobs with `archived = false` by default. 
- And idk what you mean by this: "combine that with what we did for jobs.getBuilds maybe"

2016-09-19 20:16 UTC, stjohnjohnson commented on lib/job.js
> +            return -1;
Maybe return `null`?

2016-09-19 20:18 UTC, stjohnjohnson commented on lib/job.js
> +            return -1;
Can we make this into a getter that is stored on first access?  Otherwise the sort function below will be more expensive then it needs to be.

2016-09-19 20:18 UTC, stjohnjohnson requested changes
Just one more piece of feedback

2016-09-19 20:21 UTC, d2lam commented on lib/job.js
> +            return -1;
Hmmm I didn't want it to be a getter because not every job is a PR, so it's weird that every job has a get PR number. But it's fine.

2016-09-19 21:50 UTC, d2lam commented on lib/job.js
> +            return -1;
@stjohnjohnson  I addressed this

2016-09-19 22:52 UTC, stjohnjohnson approved these changes
LGTM

2016-09-20 20:38 UTC, petey commented on lib/job.js
> +        delete this.prNum;
Why is this so heavy-handed?

The logic in the getter doesn't seem that complicated that it needs to be memoized.
```
return this.isPR() ? parseInt(this.name.slice(START_INDEX), 10) : null;
```

2016-09-20 20:51 UTC, d2lam commented on lib/job.js
> +        delete this.prNum;
@petey addressed.

2016-09-20 20:54 UTC, stjohnjohnson approved these changes
Suuure

2016-09-20 20:55 UTC, petey commented
👍  
![fetch_me_my_hat_jeeves_](https://cloud.githubusercontent.com/assets/78533/18688581/dc611174-7f39-11e6-8298-7cd9cc130146.gif)

2016-09-20 20:55 UTC, merged